basic_messages:
  - name: start
    text: Я бот-помощник
  - name: unknown_message
    text: Неизвестное сообщение

- key: hello_message
  text: "{{username}}, добро пожаловать к нам "
  catch_commands:
    - /start
    - /help
  